package Inge2.voto_virtual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.ThemeResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Table;
import com.vaadin.ui.Upload;
import com.vaadin.ui.VerticalLayout;

public class CargarPadron extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_4;
	@AutoGenerated
	private Button button_3;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_3;
	@AutoGenerated
	private Button button_2;
	@AutoGenerated
	private VerticalLayout verticalLayout_5;
	@AutoGenerated
	private Table table_1;
	@AutoGenerated
	private CheckBox checkBox_2;
	@AutoGenerated
	private VerticalLayout verticalLayout_4;
	@AutoGenerated
	private Upload upload_1;
	@AutoGenerated
	private CheckBox checkBox_1;
	@AutoGenerated
	private VerticalLayout verticalLayout_3;
	@AutoGenerated
	private Label label_2;
	@AutoGenerated
	private VerticalLayout verticalLayout_1;
	@AutoGenerated
	private Embedded embedded_1;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public CargarPadron() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		upload_1.setButtonCaption("Subir padrón");
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// verticalLayout_1
		verticalLayout_1 = buildVerticalLayout_1();
		mainLayout.addComponent(verticalLayout_1, "top:20.0px;left:20.0px;");
		
		// verticalLayout_3
		verticalLayout_3 = buildVerticalLayout_3();
		mainLayout.addComponent(verticalLayout_3, "top:80.0px;left:20.0px;");
		
		// verticalLayout_4
		verticalLayout_4 = buildVerticalLayout_4();
		mainLayout.addComponent(verticalLayout_4, "top:120.0px;left:20.0px;");
		
		// verticalLayout_5
		verticalLayout_5 = buildVerticalLayout_5();
		mainLayout.addComponent(verticalLayout_5, "top:180.0px;left:20.0px;");
		
		// horizontalLayout_3
		horizontalLayout_3 = buildHorizontalLayout_3();
		mainLayout.addComponent(horizontalLayout_3, "top:400.0px;left:20.0px;");
		
		// horizontalLayout_4
		horizontalLayout_4 = buildHorizontalLayout_4();
		mainLayout
				.addComponent(horizontalLayout_4, "top:400.0px;left:360.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_1() {
		// common part: create layout
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("580px");
		verticalLayout_1.setHeight("60px");
		verticalLayout_1.setMargin(false);
		
		// embedded_1
		embedded_1 = new Embedded();
		embedded_1.setImmediate(false);
		embedded_1.setWidth("100.0%");
		embedded_1.setHeight("100.0%");
		embedded_1.setSource(new ThemeResource("img/component/padron.jpg"));
		embedded_1.setType(1);
		embedded_1.setMimeType("image/jpg");
		verticalLayout_1.addComponent(embedded_1);
		verticalLayout_1.setExpandRatio(embedded_1, 1.0f);
		
		return verticalLayout_1;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_3() {
		// common part: create layout
		verticalLayout_3 = new VerticalLayout();
		verticalLayout_3.setImmediate(false);
		verticalLayout_3.setWidth("581px");
		verticalLayout_3.setHeight("40px");
		verticalLayout_3.setMargin(false);
		
		// label_2
		label_2 = new Label();
		label_2.setImmediate(false);
		label_2.setWidth("-1px");
		label_2.setHeight("-1px");
		label_2.setValue("Herramienta de carga del padrón electoral");
		verticalLayout_3.addComponent(label_2);
		verticalLayout_3.setComponentAlignment(label_2, new Alignment(48));
		
		return verticalLayout_3;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_4() {
		// common part: create layout
		verticalLayout_4 = new VerticalLayout();
		verticalLayout_4.setImmediate(false);
		verticalLayout_4.setWidth("580px");
		verticalLayout_4.setHeight("60px");
		verticalLayout_4.setMargin(false);
		
		// checkBox_1
		checkBox_1 = new CheckBox();
		checkBox_1
				.setCaption("Buscar y subir un archivo CSV con la información del padrón:");
		checkBox_1.setImmediate(false);
		checkBox_1.setWidth("-1px");
		checkBox_1.setHeight("-1px");
		verticalLayout_4.addComponent(checkBox_1);
		
		// upload_1
		upload_1 = new Upload();
		upload_1.setImmediate(false);
		upload_1.setWidth("75.56%");
		upload_1.setHeight("-1px");
		verticalLayout_4.addComponent(upload_1);
		verticalLayout_4.setComponentAlignment(upload_1, new Alignment(24));
		
		return verticalLayout_4;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_5() {
		// common part: create layout
		verticalLayout_5 = new VerticalLayout();
		verticalLayout_5.setImmediate(false);
		verticalLayout_5.setWidth("581px");
		verticalLayout_5.setHeight("220px");
		verticalLayout_5.setMargin(false);
		
		// checkBox_2
		checkBox_2 = new CheckBox();
		checkBox_2.setCaption("Ingresar el padrón manualmente:");
		checkBox_2.setImmediate(false);
		checkBox_2.setWidth("-1px");
		checkBox_2.setHeight("-1px");
		verticalLayout_5.addComponent(checkBox_2);
		
		// table_1
		table_1 = new Table();
		table_1.setImmediate(false);
		table_1.setWidth("93.4%");
		table_1.setHeight("100.0%");
		table_1.setInvalidAllowed(false);
		verticalLayout_5.addComponent(table_1);
		verticalLayout_5.setExpandRatio(table_1, 1.0f);
		verticalLayout_5.setComponentAlignment(table_1, new Alignment(24));
		
		return verticalLayout_5;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_3() {
		// common part: create layout
		horizontalLayout_3 = new HorizontalLayout();
		horizontalLayout_3.setImmediate(false);
		horizontalLayout_3.setWidth("240px");
		horizontalLayout_3.setHeight("43px");
		horizontalLayout_3.setMargin(false);
		
		// button_2
		button_2 = new Button();
		button_2.setCaption("<< Regresar");
		button_2.setImmediate(true);
		button_2.setWidth("-1px");
		button_2.setHeight("-1px");
		horizontalLayout_3.addComponent(button_2);
		horizontalLayout_3.setComponentAlignment(button_2, new Alignment(10));
		
		return horizontalLayout_3;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_4() {
		// common part: create layout
		horizontalLayout_4 = new HorizontalLayout();
		horizontalLayout_4.setImmediate(false);
		horizontalLayout_4.setWidth("241px");
		horizontalLayout_4.setHeight("40px");
		horizontalLayout_4.setMargin(false);
		
		// button_3
		button_3 = new Button();
		button_3.setCaption("Continuar >>");
		button_3.setImmediate(true);
		button_3.setWidth("-1px");
		button_3.setHeight("-1px");
		horizontalLayout_4.addComponent(button_3);
		horizontalLayout_4.setComponentAlignment(button_3, new Alignment(9));
		
		return horizontalLayout_4;
	}

}
