package Inge2.voto_virtual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Item;
import com.vaadin.data.util.sqlcontainer.SQLContainer;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Window;

public class ElegirEvento extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Button button_3;
	@AutoGenerated
	private Label label_2;
	@AutoGenerated
	private ComboBox comboBox_2;
	@AutoGenerated
	private Button button_2;
	@AutoGenerated
	private Button button_1;
	@AutoGenerated
	private ComboBox comboBox_1;
	@AutoGenerated
	private Label label_1;
	private Conexion conexion;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public ElegirEvento() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		PonerEventos();
		button_1.addClickListener(new Button.ClickListener() {
			public void buttonClick(ClickEvent event) {
				Item item = comboBox_1.getItem(comboBox_1.getValue());
				String idEvento = item.getItemProperty("id_evento").toString();
				int idEventoInt= Integer.parseInt(idEvento);
				
				String valor = (String) comboBox_2.getValue();
				
				final Window w = new Window("Resultados de Evento");
				w.setContent(new MostrarResultados(idEventoInt, valor));
				w.setWidth("1300px");
				w.setHeight("600px");
				w.center();
				// w.setPositionX(200); w.setPositionY(100);
				// w.setClosable(false);
				// ui.getContent().setEnabled(false);
				MyVaadinUI.getCurrent().addWindow(w);
				// cbd.closePool();	
			}
		});
		
		button_2.addClickListener(new Button.ClickListener() {
			public void buttonClick(ClickEvent event) {
				MyVaadinUI.getCurrent().setContent(new VentanaPrincipal());
			}
		});
		
	}
	
	private void PonerEventos(){
		  comboBox_2.addItem("Elección");
		  comboBox_2.addItem("Plebiscito");
		  button_3.addClickListener(new Button.ClickListener() {
				
				@Override
				public void buttonClick(ClickEvent event) {
					// TODO Auto-generated method stub
					String valor = (String) comboBox_2.getValue();
					if(valor=="Plebiscito"){
						String consulta = "SELECT nombre, id_evento FROM plebiscito;";
						 conexion = new Conexion("rebeca", "ramirez.arroyo");
						 if(conexion!=null){
							  SQLContainer resultado = conexion.consulta(consulta);
							  if(resultado != null){
								  
								  comboBox_1.setInputPrompt("Seleccione un evento");
								  comboBox_1.setContainerDataSource(resultado);
								  comboBox_1.setItemCaptionPropertyId("nombre");
							  }
						 }
						
					}
					if(valor=="Elección"){
						String consulta = "SELECT motivo, id_evento FROM eleccion;";
						 conexion = new Conexion("rebeca", "ramirez.arroyo");
						 if(conexion!=null){
							  SQLContainer resultado = conexion.consulta(consulta);
							  if(resultado != null){
								  
								  comboBox_1.setInputPrompt("Seleccione un evento");
								  comboBox_1.setContainerDataSource(resultado);
								  comboBox_1.setItemCaptionPropertyId("motivo");
							  }
						 }
						
					}
					

					
					
				}
				
			  });


	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("520px");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("520px");
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("Elegir evento a consultar");
		mainLayout.addComponent(label_1, "top:242.0px;left:60.0px;");
		
		// comboBox_1
		comboBox_1 = new ComboBox();
		comboBox_1.setImmediate(false);
		comboBox_1.setWidth("-1px");
		comboBox_1.setHeight("-1px");
		mainLayout.addComponent(comboBox_1, "top:296.0px;left:120.0px;");
		
		// button_1
		button_1 = new Button();
		button_1.setCaption("Consultar");
		button_1.setImmediate(true);
		button_1.setWidth("-1px");
		button_1.setHeight("-1px");
		mainLayout.addComponent(button_1, "top:294.0px;left:380.0px;");
		
		// button_2
		button_2 = new Button();
		button_2.setCaption("Regresar");
		button_2.setImmediate(true);
		button_2.setWidth("-1px");
		button_2.setHeight("-1px");
		mainLayout.addComponent(button_2, "top:394.0px;left:279.0px;");
		
		// comboBox_2
		comboBox_2 = new ComboBox();
		comboBox_2.setImmediate(false);
		comboBox_2.setWidth("-1px");
		comboBox_2.setHeight("-1px");
		mainLayout.addComponent(comboBox_2, "top:140.0px;left:124.0px;");
		
		// label_2
		label_2 = new Label();
		label_2.setImmediate(false);
		label_2.setWidth("-1px");
		label_2.setHeight("-1px");
		label_2.setValue("Elija tipo de evento ");
		mainLayout.addComponent(label_2, "top:80.0px;left:60.0px;");
		
		// button_3
		button_3 = new Button();
		button_3.setCaption("Elegir");
		button_3.setImmediate(true);
		button_3.setWidth("-1px");
		button_3.setHeight("-1px");
		mainLayout.addComponent(button_3, "top:140.0px;left:374.0px;");
		
		return mainLayout;
	}

}
