package Inge2.voto_virtual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;

public class ModificadorEventos extends CustomComponent {

	private VentanaListarEventos listarEventos;
	private String usuario = "112345678";
	@AutoGenerated
	private AbsoluteLayout mainLayout;

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public ModificadorEventos(String c) {
		usuario = c;
		buildMainLayout();
		setCompositionRoot(mainLayout);
		listarEventos = new VentanaListarEventos();		
		this.generarConsultas();
		listarEventos.setVentanaToGo(false);
		listarEventos.iniciar();
		MyVaadinUI.getCurrent().setContent(listarEventos);
		// TODO add user code here
	}
	
	private void generarConsultas(){
		listarEventos.setCondicionTabla1("cedula_creador = '"+usuario+"' and (requisitos_inicio <= current_date AND requisitos_fin >= current_date)");
		//"select id_evento, motivo from persona_en_padron, eleccion " +
				//"where cedula = '" + usuario +"' and id_padron = padron and  votacion_fin < current_date");
		listarEventos.setCondicionTabla2("cedula_creador = '"+usuario+"' and (requisitos_inicio <= current_date AND requisitos_fin >= current_date)");
				//"select id_evento, nombre from persona_en_padron, plebiscito" +
				//"where cedula = '" + usuario +"' and id_padron = padron and  votacion_fin < current_date");
		
	}
	
	@AutoGenerated
	private void buildMainLayout() {
		// the main layout and components will be created here
		mainLayout = new AbsoluteLayout();
	}

}
