package Inge2.voto_virtual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Item;
import com.vaadin.data.util.sqlcontainer.SQLContainer;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;

public class MostrarInfoEvento extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Button button_1;
	@AutoGenerated
	private Label label_13;
	@AutoGenerated
	private Label label_12;
	@AutoGenerated
	private Label label_11;
	@AutoGenerated
	private Label label_10;
	@AutoGenerated
	private Label label_9;
	@AutoGenerated
	private Label label_8;
	@AutoGenerated
	private Label label_7;
	@AutoGenerated
	private Label label_6;
	@AutoGenerated
	private Label label_5;
	@AutoGenerated
	private Label label_4;
	@AutoGenerated
	private Label label_3;
	@AutoGenerated
	private Label label_2;
	@AutoGenerated
	private Label label_1;
	private int idEvento;
	private Conexion conexion;
	private String valorEvento;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatical		|ly regenerated by the
	 * visual editor.
	 */
	public MostrarInfoEvento(int idEv, String valor) {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		valorEvento = valor;
		idEvento = idEv;
		ponerInfo();
		button_1.addClickListener(new Button.ClickListener() {
			
			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				MyVaadinUI.getCurrent().setContent(new VentanaPrincipal());
			}
			
		  });
		
	}
	
	private void ponerInfo(){
		if(valorEvento=="Plebiscito"){
			String consulta = "SELECT * FROM plebiscito WHERE id_evento="+idEvento+";";
			 conexion = new Conexion("rebeca", "ramirez.arroyo");
			 if(conexion!=null){
				  SQLContainer resultado = conexion.consulta(consulta);
				  if(resultado != null){
					  resultado.firstItemId();
					  Item item = resultado.getItem(resultado.firstItemId());
					  String res = item.getItemProperty("nombre").toString();
					  label_1.setValue(res);
					  String res2 = item.getItemProperty("reg_tend_inicio").toString();
					  label_3.setValue(res2);
					  String res3 = item.getItemProperty("reg_tend_fin").toString();
					  label_5.setValue(res3);
					  String res4 = item.getItemProperty("requisitos_inicio").toString();
					  label_7.setValue(res4);
					  String res5 = item.getItemProperty("requisitos_fin").toString();
					  label_9.setValue(res5);
					  String res6 = item.getItemProperty("votacion_inicio").toString();
					  label_11.setValue(res6);
					  String res7 = item.getItemProperty("votacion_fin").toString();
					  label_13.setValue(res7);
					  
					
				
				  }
			 }
		}
		if(valorEvento=="Elección"){
			String consulta = "SELECT * FROM eleccion WHERE id_evento="+idEvento+";";
			 conexion = new Conexion("rebeca", "ramirez.arroyo");
			 if(conexion!=null){
				  SQLContainer resultado = conexion.consulta(consulta);
				  if(resultado != null){
					  resultado.firstItemId();
					  Item item = resultado.getItem(resultado.firstItemId());
					  String res = item.getItemProperty("motivo").toString();
					  label_1.setValue(res);
					  String res2 = item.getItemProperty("reg_tend_inicio").toString();
					  label_3.setValue(res2);
					  String res3 = item.getItemProperty("reg_tend_fin").toString();
					  label_5.setValue(res3);
					  String res4 = item.getItemProperty("requisitos_inicio").toString();
					  label_7.setValue(res4);
					  String res5 = item.getItemProperty("requisitos_fin").toString();
					  label_9.setValue(res5);
					  String res6 = item.getItemProperty("votacion_inicio").toString();
					  label_11.setValue(res6);
					  String res7 = item.getItemProperty("votacion_fin").toString();
					  label_13.setValue(res7);
					  
					
					
				
				  }
			 }
			
		}
		
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("720px");
		mainLayout.setHeight("520px");
		
		// top-level component properties
		setWidth("720px");
		setHeight("520px");
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("NombreEvento");
		mainLayout.addComponent(label_1, "top:40.0px;left:60.0px;");
		
		// label_2
		label_2 = new Label();
		label_2.setImmediate(false);
		label_2.setWidth("-1px");
		label_2.setHeight("-1px");
		label_2.setValue("Periodo de registro de tendencias");
		mainLayout.addComponent(label_2, "top:100.0px;left:100.0px;");
		
		// label_3
		label_3 = new Label();
		label_3.setImmediate(false);
		label_3.setWidth("-1px");
		label_3.setHeight("-1px");
		label_3.setValue("fechaInicio");
		mainLayout.addComponent(label_3, "top:140.0px;left:140.0px;");
		
		// label_4
		label_4 = new Label();
		label_4.setImmediate(false);
		label_4.setWidth("-1px");
		label_4.setHeight("-1px");
		label_4.setValue("hasta");
		mainLayout.addComponent(label_4, "top:142.0px;left:240.0px;");
		
		// label_5
		label_5 = new Label();
		label_5.setImmediate(false);
		label_5.setWidth("-1px");
		label_5.setHeight("-1px");
		label_5.setValue("fechaFinal");
		mainLayout.addComponent(label_5, "top:140.0px;left:310.0px;");
		
		// label_6
		label_6 = new Label();
		label_6.setImmediate(false);
		label_6.setWidth("-1px");
		label_6.setHeight("-1px");
		label_6.setValue("Fecha final de modificaciones");
		mainLayout.addComponent(label_6, "top:202.0px;left:100.0px;");
		
		// label_7
		label_7 = new Label();
		label_7.setImmediate(false);
		label_7.setWidth("-1px");
		label_7.setHeight("-1px");
		label_7.setValue("fechaInicio");
		mainLayout.addComponent(label_7, "top:242.0px;left:140.0px;");
		
		// label_8
		label_8 = new Label();
		label_8.setImmediate(false);
		label_8.setWidth("-1px");
		label_8.setHeight("-1px");
		label_8.setValue("hasta");
		mainLayout.addComponent(label_8, "top:242.0px;left:240.0px;");
		
		// label_9
		label_9 = new Label();
		label_9.setImmediate(false);
		label_9.setWidth("-1px");
		label_9.setHeight("-1px");
		label_9.setValue("fechaFinal");
		mainLayout.addComponent(label_9, "top:242.0px;left:310.0px;");
		
		// label_10
		label_10 = new Label();
		label_10.setImmediate(false);
		label_10.setWidth("-1px");
		label_10.setHeight("-1px");
		label_10.setValue("Fecha de votación del evento");
		mainLayout.addComponent(label_10, "top:302.0px;left:100.0px;");
		
		// label_11
		label_11 = new Label();
		label_11.setImmediate(false);
		label_11.setWidth("-1px");
		label_11.setHeight("-1px");
		label_11.setValue("fechaInicio");
		mainLayout.addComponent(label_11, "top:340.0px;left:142.0px;");
		
		// label_12
		label_12 = new Label();
		label_12.setImmediate(false);
		label_12.setWidth("-1px");
		label_12.setHeight("-1px");
		label_12.setValue("hasta");
		mainLayout.addComponent(label_12, "top:340.0px;left:240.0px;");
		
		// label_13
		label_13 = new Label();
		label_13.setImmediate(false);
		label_13.setWidth("-1px");
		label_13.setHeight("-1px");
		label_13.setValue("fechaFinal");
		mainLayout.addComponent(label_13, "top:340.0px;left:310.0px;");
		
		// button_1
		button_1 = new Button();
		button_1.setCaption("Regresar");
		button_1.setImmediate(true);
		button_1.setWidth("-1px");
		button_1.setHeight("-1px");
		mainLayout.addComponent(button_1, "top:302.0px;left:533.0px;");
		
		return mainLayout;
	}

}
