package Inge2.voto_virtual;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Notification;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TextArea;

public class VentanaModificarEleccion extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private AbsoluteLayout absoluteLayout_2;
	@AutoGenerated
	private Button button_3;
	@AutoGenerated
	private Label label_6;
	@AutoGenerated
	private Button button_2;
	@AutoGenerated
	private Button button_1;
	@AutoGenerated
	private Label label_9;
	@AutoGenerated
	private PopupDateField popupDateField_6;
	@AutoGenerated
	private PopupDateField popupDateField_5;
	@AutoGenerated
	private Label label_8;
	@AutoGenerated
	private Label label_7;
	@AutoGenerated
	private PopupDateField popupDateField_4;
	@AutoGenerated
	private Label label_5;
	@AutoGenerated
	private Label label_4;
	@AutoGenerated
	private Label label_3;
	@AutoGenerated
	private Label label_2;
	@AutoGenerated
	private PopupDateField popupDateField_3;
	@AutoGenerated
	private PopupDateField popupDateField_2;
	@AutoGenerated
	private PopupDateField popupDateField_1;
	@AutoGenerated
	private TextArea textArea_1;
	@AutoGenerated
	private Label label_1;
	public String evento;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public VentanaModificarEleccion(String ev) {
		evento = ev;
		buildMainLayout();
		setCompositionRoot(mainLayout);
		textArea_1.focus();
		// Boton Regresar
		button_1.addClickListener(new Button.ClickListener() {
			public void buttonClick(ClickEvent event) {
				MyVaadinUI.getCurrent().setContent(new VentanaPrincipal());
			}
		});
		// Boton Aceptar
		button_2.addClickListener(new Button.ClickListener() {
			public void buttonClick(ClickEvent event) {
				if (guardar()) {
					MyVaadinUI.getCurrent().setContent(new VentanaPrincipal());
				} else {
					label_6.setValue("Error al crear el evento, favor revise los datos");
				}
			}
		});
		this.llenarCampos();
		button_3.addClickListener(new Button.ClickListener() {
			public void buttonClick(ClickEvent event) {
				String sql = "DELETE FROM eleccion WHERE id_evento = " + evento + ";";
				Conexion con = new Conexion("eduardo", "steiner.garro");
				if(con.ejecutar(sql)){
					Notification.show(
		                    "Se eliminó el evento", Notification.TYPE_WARNING_MESSAGE);
				}
			}
		});
	}

	public boolean guardar() {
		SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
		String motivo = textArea_1.getValue();
		String f1 = sdf.format(popupDateField_1.getValue());
		String f2 = sdf.format(popupDateField_2.getValue());
		String f3 = sdf.format(popupDateField_3.getValue());
		String f4 = sdf.format(popupDateField_4.getValue());
		String f5 = sdf.format(popupDateField_5.getValue());
		String f6 = sdf.format(popupDateField_6.getValue());
		String sql = "UPDATE eleccion " + "SET motivo= '" + motivo
				+ "', reg_tend_inicio= '" + f1 + "', reg_tend_fin='" + f2
				+ "', requisitos_inicio='" + f3 + "', requisitos_fin='" + f4
				+ "', votacion_inicio='" + f5 + "', votacion_fin='" + f6
				+ "' WHERE id_evento = " + evento + ";";
		System.out.println(sql);
		Conexion con = new Conexion("eduardo", "steiner.garro");
		boolean exito = con.ejecutar(sql);
		return exito;
	}

	private Date transformDate(String original) {
		//String edited = "";
		String[] parts = original.split("-");
		//edited = parts[2] + "/" + parts[1] + "/" + parts[0];
		
		Date d = new Date();		
		d.setDate(Integer.parseInt(parts[2]));
		d.setMonth(Integer.parseInt(parts[1])-1);
		d.setYear(Integer.parseInt(parts[0])-1900);
		//System.out.println("original "+original+" date "+d.toString());
		return d;
	}

	public void llenarCampos() {
		String consulta = "select * from eleccion where id_Evento = " + evento;
		// System.out.println(consulta);
		Conexion con = new Conexion("eduardo", "steiner.garro");
		ArrayList<ArrayList<String>> resultado = con.consultarArray(consulta);
		ArrayList<String> datos = resultado.get(0);
		// textArea_1.setCaption(datos.get(1));
		textArea_1.setValue(datos.get(1));
		// SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
		// System.out.println(datos.get(2));
		//System.out.println((this.transformDate(datos.get(2))).toString());
		//popupDateField_1.setDateFormat("yy/mm/dd");
		popupDateField_1.setValue((this.transformDate(datos.get(2))));
		
		//popupDateField_2.setDateFormat("mm/dd/yy");
		popupDateField_2.setValue((this.transformDate(datos.get(3))));
		//popupDateField_3.setDateFormat("mm/dd/yyyy");
		popupDateField_3.setValue((this.transformDate(datos.get(4))));
		//popupDateField_4.setDateFormat("dd/mm/yy");
		popupDateField_4.setValue((this.transformDate(datos.get(5))));
		//popupDateField_5.setDateFormat("dd/mm/yyyy");
		popupDateField_5.setValue((this.transformDate(datos.get(6))));
		popupDateField_6.setValue((this.transformDate(datos.get(7))));

	}


	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("598px");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("598px");
		
		// absoluteLayout_2
		absoluteLayout_2 = buildAbsoluteLayout_2();
		mainLayout.addComponent(absoluteLayout_2, "top:-160.0px;left:60.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsoluteLayout_2() {
		// common part: create layout
		absoluteLayout_2 = new AbsoluteLayout();
		absoluteLayout_2.setImmediate(false);
		absoluteLayout_2.setWidth("540px");
		absoluteLayout_2.setHeight("460px");
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("100.0%");
		label_1.setHeight("-1px");
		label_1.setValue("Nuevo evento \"Elección\"");
		absoluteLayout_2.addComponent(label_1,
				"top:20.0px;right:189.0px;left:191.0px;");
		
		// textArea_1
		textArea_1 = new TextArea();
		textArea_1.setImmediate(false);
		textArea_1.setWidth("440px");
		textArea_1.setHeight("-1px");
		absoluteLayout_2.addComponent(textArea_1, "top:80.0px;left:60.0px;");
		
		// popupDateField_1
		popupDateField_1 = new PopupDateField();
		popupDateField_1.setImmediate(false);
		popupDateField_1.setWidth("140px");
		popupDateField_1.setHeight("-1px");
		popupDateField_1.setTabIndex(1);
		absoluteLayout_2.addComponent(popupDateField_1,
				"top:200.0px;left:200.0px;");
		
		// popupDateField_2
		popupDateField_2 = new PopupDateField();
		popupDateField_2.setImmediate(false);
		popupDateField_2.setWidth("140px");
		popupDateField_2.setHeight("-1px");
		popupDateField_2.setTabIndex(2);
		absoluteLayout_2.addComponent(popupDateField_2,
				"top:200.0px;left:360.0px;");
		
		// popupDateField_3
		popupDateField_3 = new PopupDateField();
		popupDateField_3.setImmediate(false);
		popupDateField_3.setWidth("140px");
		popupDateField_3.setHeight("-1px");
		popupDateField_3.setTabIndex(3);
		absoluteLayout_2.addComponent(popupDateField_3,
				"top:240.0px;left:200.0px;");
		
		// label_2
		label_2 = new Label();
		label_2.setImmediate(false);
		label_2.setWidth("-1px");
		label_2.setHeight("-1px");
		label_2.setValue("Fecha inicial");
		absoluteLayout_2.addComponent(label_2, "top:176.0px;left:227.0px;");
		
		// label_3
		label_3 = new Label();
		label_3.setImmediate(false);
		label_3.setWidth("-1px");
		label_3.setHeight("-1px");
		label_3.setValue("Fecha final");
		absoluteLayout_2.addComponent(label_3, "top:176.0px;left:387.0px;");
		
		// label_4
		label_4 = new Label();
		label_4.setImmediate(false);
		label_4.setWidth("-1px");
		label_4.setHeight("-1px");
		label_4.setValue("Votación :");
		absoluteLayout_2.addComponent(label_4, "top:280.0px;left:60.0px;");
		
		// label_5
		label_5 = new Label();
		label_5.setImmediate(false);
		label_5.setWidth("-1px");
		label_5.setHeight("-1px");
		label_5.setValue("Descripción del evento (motivo):");
		absoluteLayout_2.addComponent(label_5, "top:62.0px;left:40.0px;");
		
		// popupDateField_4
		popupDateField_4 = new PopupDateField();
		popupDateField_4.setImmediate(false);
		popupDateField_4.setWidth("140px");
		popupDateField_4.setHeight("-1px");
		absoluteLayout_2.addComponent(popupDateField_4,
				"top:241.0px;left:360.0px;");
		
		// label_7
		label_7 = new Label();
		label_7.setImmediate(false);
		label_7.setWidth("-1px");
		label_7.setHeight("-1px");
		label_7.setValue("Cumplimiento requisitos:");
		absoluteLayout_2.addComponent(label_7, "top:240.0px;left:59.0px;");
		
		// label_8
		label_8 = new Label();
		label_8.setImmediate(false);
		label_8.setWidth("-1px");
		label_8.setHeight("-1px");
		label_8.setValue("Inscipción de tendencias:");
		absoluteLayout_2.addComponent(label_8, "top:200.0px;left:60.0px;");
		
		// popupDateField_5
		popupDateField_5 = new PopupDateField();
		popupDateField_5.setImmediate(false);
		popupDateField_5.setWidth("140px");
		popupDateField_5.setHeight("-1px");
		popupDateField_5.setTabIndex(3);
		absoluteLayout_2.addComponent(popupDateField_5,
				"top:277.0px;left:200.0px;");
		
		// popupDateField_6
		popupDateField_6 = new PopupDateField();
		popupDateField_6.setImmediate(false);
		popupDateField_6.setWidth("140px");
		popupDateField_6.setHeight("-1px");
		absoluteLayout_2.addComponent(popupDateField_6,
				"top:277.0px;left:360.0px;");
		
		// label_9
		label_9 = new Label();
		label_9.setImmediate(false);
		label_9.setWidth("-1px");
		label_9.setHeight("-1px");
		label_9.setValue("Etapas:");
		absoluteLayout_2.addComponent(label_9, "top:176.0px;left:40.0px;");
		
		// button_1
		button_1 = new Button();
		button_1.setCaption("<< Regresar");
		button_1.setImmediate(true);
		button_1.setWidth("180px");
		button_1.setHeight("-1px");
		absoluteLayout_2.addComponent(button_1, "top:411.0px;left:80.0px;");
		
		// button_2
		button_2 = new Button();
		button_2.setCaption("Guardar >>");
		button_2.setImmediate(true);
		button_2.setWidth("180px");
		button_2.setHeight("-1px");
		absoluteLayout_2.addComponent(button_2, "top:411.0px;left:280.0px;");
		
		// label_6
		label_6 = new Label();
		label_6.setImmediate(false);
		label_6.setWidth("300px");
		label_6.setHeight("20px");
		label_6.setValue(" ");
		absoluteLayout_2.addComponent(label_6, "top:380.0px;left:120.0px;");
		
		// button_3
		button_3 = new Button();
		button_3.setCaption("Cancelar evento");
		button_3.setImmediate(true);
		button_3.setWidth("280px");
		button_3.setHeight("-1px");
		absoluteLayout_2.addComponent(button_3, "top:345.0px;left:140.0px;");
		
		return absoluteLayout_2;
	}

}
