package Inge2.voto_virtual;


import com.vaadin.annotations.AutoGenerated;
import com.vaadin.event.MouseEvents.ClickEvent;
import com.vaadin.event.MouseEvents.ClickListener;
import com.vaadin.server.ThemeResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Link;

@SuppressWarnings("serial")
public class VentanaPrincipal extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private GridLayout gridLayout_1;
	@AutoGenerated
	private Link link_4;
	@AutoGenerated
	private Link link_6;
	@AutoGenerated
	private Link link_3;
	@AutoGenerated
	private Embedded embedded_4;
	@AutoGenerated
	private Embedded embedded_6;
	@AutoGenerated
	private Embedded embedded_2;
	@AutoGenerated
	private Link link_2;
	@AutoGenerated
	private Link link_5;
	@AutoGenerated
	private Link link_1;
	@AutoGenerated
	private Embedded embedded_3;
	@AutoGenerated
	private Embedded embedded_5;
	@AutoGenerated
	private Embedded embedded_1;
	
	public int cedula = 112345678;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
		
	public VentanaPrincipal() {		
		buildMainLayout();
		setCompositionRoot(mainLayout);

		embedded_1.addClickListener(new ClickListener(){
			@Override
			public void click(ClickEvent event) {
				MyVaadinUI.getCurrent().setContent(new CrearEvento());
			}
		});
		embedded_2.addClickListener(new ClickListener(){
			@Override
			public void click(ClickEvent event) {
				MyVaadinUI.getCurrent().setContent(new VentanaMostrarEventosEnVotacion());
			}
		});
		embedded_3.addClickListener(new ClickListener(){
			@Override
			public void click(ClickEvent event) {
				MyVaadinUI.getCurrent().setContent(new AgregarTendencia()); //new AgregarTendencia()
			}
		});
		embedded_4.addClickListener(new ClickListener(){
			@Override
			public void click(ClickEvent event) {
				MyVaadinUI.getCurrent().setContent(new ElegirEvento());
			}
		});
		embedded_5.addClickListener(new ClickListener(){
			@Override
			public void click(ClickEvent event) {
				MyVaadinUI.getCurrent().setContent(new ListaEventos());
			}
		});
		embedded_6.addClickListener(new ClickListener(){
			@Override
			public void click(ClickEvent event) {
				ModificadorEventos m = new ModificadorEventos(cedula+"");
			}
		});
		
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setCaption("Crear un evento");
		mainLayout.setImmediate(false);
		mainLayout.setWidth("819px");
		mainLayout.setHeight("545px");
		
		// top-level component properties
		setWidth("819px");
		setHeight("545px");
		
		// gridLayout_1
		gridLayout_1 = buildGridLayout_1();
		mainLayout.addComponent(gridLayout_1, "top:80.0px;left:-12.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_1() {
		// common part: create layout
		gridLayout_1 = new GridLayout();
		gridLayout_1.setImmediate(false);
		gridLayout_1.setWidth("869px");
		gridLayout_1.setHeight("480px");
		gridLayout_1.setMargin(false);
		gridLayout_1.setColumns(3);
		gridLayout_1.setRows(4);
		
		// embedded_1
		embedded_1 = new Embedded();
		embedded_1.setImmediate(false);
		embedded_1.setWidth("180px");
		embedded_1.setHeight("140px");
		embedded_1.setSource(new ThemeResource("img/component/evento.png"));
		embedded_1.setType(1);
		embedded_1.setMimeType("image/png");
		gridLayout_1.addComponent(embedded_1, 0, 0);
		gridLayout_1.setComponentAlignment(embedded_1, new Alignment(48));
		
		// embedded_5
		embedded_5 = new Embedded();
		embedded_5.setImmediate(false);
		embedded_5.setWidth("180px");
		embedded_5.setHeight("140px");
		embedded_5.setSource(new ThemeResource("img/component/infoev.png"));
		embedded_5.setType(1);
		embedded_5.setMimeType("image/png");
		gridLayout_1.addComponent(embedded_5, 1, 0);
		gridLayout_1.setComponentAlignment(embedded_5, new Alignment(48));
		
		// embedded_3
		embedded_3 = new Embedded();
		embedded_3.setImmediate(false);
		embedded_3.setWidth("180px");
		embedded_3.setHeight("140px");
		embedded_3.setSource(new ThemeResource("img/component/tendencia.png"));
		embedded_3.setType(1);
		embedded_3.setMimeType("image/png");
		gridLayout_1.addComponent(embedded_3, 2, 0);
		gridLayout_1.setComponentAlignment(embedded_3, new Alignment(48));
		
		// link_1
		link_1 = new Link();
		link_1.setCaption("Crear un evento");
		link_1.setImmediate(false);
		link_1.setWidth("-1px");
		link_1.setHeight("14px");
		gridLayout_1.addComponent(link_1, 0, 1);
		gridLayout_1.setComponentAlignment(link_1, new Alignment(48));
		
		// link_5
		link_5 = new Link();
		link_5.setCaption("Ver información de evento");
		link_5.setImmediate(false);
		link_5.setWidth("-1px");
		link_5.setHeight("-1px");
		gridLayout_1.addComponent(link_5, 1, 1);
		gridLayout_1.setComponentAlignment(link_5, new Alignment(48));
		
		// link_2
		link_2 = new Link();
		link_2.setCaption("Registrar tendencia");
		link_2.setImmediate(false);
		link_2.setWidth("-1px");
		link_2.setHeight("-1px");
		gridLayout_1.addComponent(link_2, 2, 1);
		gridLayout_1.setComponentAlignment(link_2, new Alignment(48));
		
		// embedded_2
		embedded_2 = new Embedded();
		embedded_2.setImmediate(false);
		embedded_2.setWidth("180px");
		embedded_2.setHeight("140px");
		embedded_2.setSource(new ThemeResource("img/component/eventos.png"));
		embedded_2.setType(1);
		embedded_2.setMimeType("image/png");
		gridLayout_1.addComponent(embedded_2, 0, 2);
		gridLayout_1.setComponentAlignment(embedded_2, new Alignment(48));
		
		// embedded_6
		embedded_6 = new Embedded();
		embedded_6.setImmediate(false);
		embedded_6.setWidth("180px");
		embedded_6.setHeight("140px");
		embedded_6.setSource(new ThemeResource("img/component/modificar.png"));
		embedded_6.setType(1);
		embedded_6.setMimeType("image/png");
		gridLayout_1.addComponent(embedded_6, 1, 2);
		gridLayout_1.setComponentAlignment(embedded_6, new Alignment(48));
		
		// embedded_4
		embedded_4 = new Embedded();
		embedded_4.setImmediate(false);
		embedded_4.setWidth("180px");
		embedded_4.setHeight("140px");
		embedded_4
				.setSource(new ThemeResource("img/component/estadisticas.png"));
		embedded_4.setType(1);
		embedded_4.setMimeType("image/png");
		gridLayout_1.addComponent(embedded_4, 2, 2);
		gridLayout_1.setComponentAlignment(embedded_4, new Alignment(48));
		
		// link_3
		link_3 = new Link();
		link_3.setCaption("Ver eventos");
		link_3.setImmediate(false);
		link_3.setWidth("-1px");
		link_3.setHeight("-1px");
		gridLayout_1.addComponent(link_3, 0, 3);
		gridLayout_1.setComponentAlignment(link_3, new Alignment(48));
		
		// link_6
		link_6 = new Link();
		link_6.setCaption("Modificar evento");
		link_6.setImmediate(false);
		link_6.setWidth("-1px");
		link_6.setHeight("-1px");
		gridLayout_1.addComponent(link_6, 1, 3);
		gridLayout_1.setComponentAlignment(link_6, new Alignment(48));
		
		// link_4
		link_4 = new Link();
		link_4.setCaption("Mostrar estadísticas");
		link_4.setImmediate(false);
		link_4.setWidth("-1px");
		link_4.setHeight("-1px");
		gridLayout_1.addComponent(link_4, 2, 3);
		gridLayout_1.setComponentAlignment(link_4, new Alignment(48));
		
		return gridLayout_1;
	}

}
