package Inge2.voto_virtual;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Notification;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;

public class VentanaModificarPlebiscito extends CustomComponent {


	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private AbsoluteLayout absoluteLayout_2;
	@AutoGenerated
	private Button button_4;
	@AutoGenerated
	private Label label_10;
	@AutoGenerated
	private TextArea textArea_2;
	@AutoGenerated
	private Label label_6;
	@AutoGenerated
	private TextField textField_1;
	@AutoGenerated
	private Button button_2;
	@AutoGenerated
	private Button button_1;
	@AutoGenerated
	private Label label_9;
	@AutoGenerated
	private PopupDateField popupDateField_6;
	@AutoGenerated
	private PopupDateField popupDateField_5;
	@AutoGenerated
	private Label label_8;
	@AutoGenerated
	private Label label_7;
	@AutoGenerated
	private PopupDateField popupDateField_4;
	@AutoGenerated
	private Label label_5;
	@AutoGenerated
	private Label label_4;
	@AutoGenerated
	private Label label_3;
	@AutoGenerated
	private Label label_2;
	@AutoGenerated
	private PopupDateField popupDateField_3;
	@AutoGenerated
	private PopupDateField popupDateField_2;
	@AutoGenerated
	private PopupDateField popupDateField_1;
	@AutoGenerated
	private Label label_1;
	private String evento;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public VentanaModificarPlebiscito(String e) {
		evento = e;
		buildMainLayout();
		setCompositionRoot(mainLayout);

		textField_1.focus();
		llenarCampos();
		//Boton Regresar
		button_1.addClickListener(new Button.ClickListener() {
			public void buttonClick(ClickEvent event) {
				MyVaadinUI.getCurrent().setContent(new VentanaPrincipal());
			}
		});
		//Boton Aceptar
		button_2.addClickListener(new Button.ClickListener() {
			public void buttonClick(ClickEvent event) {
				if (guardar()) {
					MyVaadinUI.getCurrent().setContent(new VentanaPrincipal());
		    	}else{
		    		label_10.setValue("Error al crear el evento, favor revise los datos");
		    	}
			}
		});
		//Boton Cancelar
		button_4.addClickListener(new Button.ClickListener() {
			public void buttonClick(ClickEvent event) {
				String sql = "DELETE FROM eleccion WHERE id_evento = " + evento + ";";
				Conexion con = new Conexion("eduardo", "steiner.garro");
				if(con.ejecutar(sql)){
					Notification.show(
		                    "Se eliminó el evento", Notification.TYPE_WARNING_MESSAGE);
				}
			}
		});
	}

	
	public boolean guardar() {
		SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
		String nombre = textField_1.getValue();
		String pregunta = textArea_2.getValue();
		String f1 = sdf.format(popupDateField_1.getValue());
		String f2 = sdf.format(popupDateField_2.getValue());
		String f3 = sdf.format(popupDateField_3.getValue());
		String f4 = sdf.format(popupDateField_4.getValue());
		String f5 = sdf.format(popupDateField_5.getValue());
		String f6 = sdf.format(popupDateField_6.getValue());
		String sql = "UPDATE plebiscito " + "SET nombre= '" + nombre
				+ "', pregunta = '"+ pregunta
				+ "', reg_tend_inicio= '" + f1 + "', reg_tend_fin='" + f2
				+ "', requisitos_inicio='" + f3 + "', requisitos_fin='" + f4
				+ "', votacion_inicio='" + f5 + "', votacion_fin='" + f6
				+ "' WHERE id_evento = " + evento + ";";
		System.out.println(sql); 
		Conexion con = new Conexion("eduardo", "steiner.garro");
		boolean exito = con.ejecutar(sql);
		return exito;
	}

	private Date transformDate(String original) {
		//String edited = "";
		String[] parts = original.split("-");
		//edited = parts[2] + "/" + parts[1] + "/" + parts[0];
		
		Date d = new Date();		
		d.setDate(Integer.parseInt(parts[2]));
		d.setMonth(Integer.parseInt(parts[1])-1);
		d.setYear(Integer.parseInt(parts[0])-1900);
		//System.out.println("original "+original+" date "+d.toString());
		return d;
	}

	public void llenarCampos() {
		String consulta = "select * from plebiscito where id_Evento = " + evento;
		// System.out.println(consulta);
		Conexion con = new Conexion("eduardo", "steiner.garro");
		ArrayList<ArrayList<String>> resultado = con.consultarArray(consulta);
		ArrayList<String> datos = resultado.get(0);
		textField_1.setValue(datos.get(1));
		textArea_2.setValue(datos.get(2));
		popupDateField_1.setValue((this.transformDate(datos.get(3))));
		
		//popupDateField_2.setDateFormat("mm/dd/yy");
		popupDateField_2.setValue((this.transformDate(datos.get(4))));
		//popupDateField_3.setDateFormat("mm/dd/yyyy");
		popupDateField_3.setValue((this.transformDate(datos.get(5))));
		//popupDateField_4.setDateFormat("dd/mm/yy");
		popupDateField_4.setValue((this.transformDate(datos.get(6))));
		//popupDateField_5.setDateFormat("dd/mm/yyyy");
		popupDateField_5.setValue((this.transformDate(datos.get(7))));
		popupDateField_6.setValue((this.transformDate(datos.get(8))));	

	}

	
	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("528px");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("528px");
		
		// absoluteLayout_2
		absoluteLayout_2 = buildAbsoluteLayout_2();
		mainLayout.addComponent(absoluteLayout_2, "top:40.0px;left:60.0px;");
		
		return mainLayout;
	}


	@AutoGenerated
	private AbsoluteLayout buildAbsoluteLayout_2() {
		// common part: create layout
		absoluteLayout_2 = new AbsoluteLayout();
		absoluteLayout_2.setImmediate(false);
		absoluteLayout_2.setWidth("540px");
		absoluteLayout_2.setHeight("460px");
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("100.0%");
		label_1.setHeight("-1px");
		label_1.setValue("Nuevo evento \"Plebiscito\"");
		absoluteLayout_2.addComponent(label_1,
				"top:20.0px;right:189.0px;left:191.0px;");
		
		// popupDateField_1
		popupDateField_1 = new PopupDateField();
		popupDateField_1.setImmediate(false);
		popupDateField_1.setWidth("140px");
		popupDateField_1.setHeight("-1px");
		popupDateField_1.setTabIndex(1);
		absoluteLayout_2.addComponent(popupDateField_1,
				"top:200.0px;left:200.0px;");
		
		// popupDateField_2
		popupDateField_2 = new PopupDateField();
		popupDateField_2.setImmediate(false);
		popupDateField_2.setWidth("140px");
		popupDateField_2.setHeight("-1px");
		popupDateField_2.setTabIndex(2);
		absoluteLayout_2.addComponent(popupDateField_2,
				"top:200.0px;left:360.0px;");
		
		// popupDateField_3
		popupDateField_3 = new PopupDateField();
		popupDateField_3.setImmediate(false);
		popupDateField_3.setWidth("140px");
		popupDateField_3.setHeight("-1px");
		popupDateField_3.setTabIndex(3);
		absoluteLayout_2.addComponent(popupDateField_3,
				"top:240.0px;left:200.0px;");
		
		// label_2
		label_2 = new Label();
		label_2.setImmediate(false);
		label_2.setWidth("-1px");
		label_2.setHeight("-1px");
		label_2.setValue("Fecha inicial");
		absoluteLayout_2.addComponent(label_2, "top:176.0px;left:227.0px;");
		
		// label_3
		label_3 = new Label();
		label_3.setImmediate(false);
		label_3.setWidth("-1px");
		label_3.setHeight("-1px");
		label_3.setValue("Fecha final");
		absoluteLayout_2.addComponent(label_3, "top:176.0px;left:387.0px;");
		
		// label_4
		label_4 = new Label();
		label_4.setImmediate(false);
		label_4.setWidth("-1px");
		label_4.setHeight("-1px");
		label_4.setValue("Votación :");
		absoluteLayout_2.addComponent(label_4, "top:280.0px;left:60.0px;");
		
		// label_5
		label_5 = new Label();
		label_5.setImmediate(false);
		label_5.setWidth("-1px");
		label_5.setHeight("-1px");
		label_5.setValue("Nombre del evento:");
		absoluteLayout_2.addComponent(label_5, "top:62.0px;left:40.0px;");
		
		// popupDateField_4
		popupDateField_4 = new PopupDateField();
		popupDateField_4.setImmediate(false);
		popupDateField_4.setWidth("140px");
		popupDateField_4.setHeight("-1px");
		absoluteLayout_2.addComponent(popupDateField_4,
				"top:241.0px;left:360.0px;");
		
		// label_7
		label_7 = new Label();
		label_7.setImmediate(false);
		label_7.setWidth("-1px");
		label_7.setHeight("-1px");
		label_7.setValue("Cumplimiento requisitos:");
		absoluteLayout_2.addComponent(label_7, "top:240.0px;left:59.0px;");
		
		// label_8
		label_8 = new Label();
		label_8.setImmediate(false);
		label_8.setWidth("-1px");
		label_8.setHeight("-1px");
		label_8.setValue("Inscipción de tendencias:");
		absoluteLayout_2.addComponent(label_8, "top:200.0px;left:60.0px;");
		
		// popupDateField_5
		popupDateField_5 = new PopupDateField();
		popupDateField_5.setImmediate(false);
		popupDateField_5.setWidth("140px");
		popupDateField_5.setHeight("-1px");
		popupDateField_5.setTabIndex(3);
		absoluteLayout_2.addComponent(popupDateField_5,
				"top:277.0px;left:200.0px;");
		
		// popupDateField_6
		popupDateField_6 = new PopupDateField();
		popupDateField_6.setImmediate(false);
		popupDateField_6.setWidth("140px");
		popupDateField_6.setHeight("-1px");
		absoluteLayout_2.addComponent(popupDateField_6,
				"top:277.0px;left:360.0px;");
		
		// label_9
		label_9 = new Label();
		label_9.setImmediate(false);
		label_9.setWidth("-1px");
		label_9.setHeight("-1px");
		label_9.setValue("Etapas:");
		absoluteLayout_2.addComponent(label_9, "top:176.0px;left:40.0px;");
		
		// button_1
		button_1 = new Button();
		button_1.setCaption("<< Regresar");
		button_1.setImmediate(true);
		button_1.setWidth("180px");
		button_1.setHeight("-1px");
		absoluteLayout_2.addComponent(button_1, "top:411.0px;left:80.0px;");
		
		// button_2
		button_2 = new Button();
		button_2.setCaption("Aceptar >>");
		button_2.setImmediate(true);
		button_2.setWidth("180px");
		button_2.setHeight("-1px");
		absoluteLayout_2.addComponent(button_2, "top:411.0px;left:280.0px;");
		
		// textField_1
		textField_1 = new TextField();
		textField_1.setImmediate(false);
		textField_1.setWidth("339px");
		textField_1.setHeight("-1px");
		absoluteLayout_2.addComponent(textField_1, "top:56.0px;left:161.0px;");
		
		// label_6
		label_6 = new Label();
		label_6.setImmediate(false);
		label_6.setWidth("120px");
		label_6.setHeight("-1px");
		label_6.setValue("Pregunta a responder:");
		absoluteLayout_2.addComponent(label_6, "top:102.0px;left:40.0px;");
		
		// textArea_2
		textArea_2 = new TextArea();
		textArea_2.setImmediate(false);
		textArea_2.setWidth("339px");
		textArea_2.setHeight("59px");
		absoluteLayout_2.addComponent(textArea_2, "top:100.0px;left:161.0px;");
		
		// label_10
		label_10 = new Label();
		label_10.setImmediate(false);
		label_10.setWidth("300px");
		label_10.setHeight("18px");
		label_10.setValue(" ");
		absoluteLayout_2.addComponent(label_10, "top:382.0px;left:120.0px;");
		
		// button_4
		button_4 = new Button();
		button_4.setCaption("Cancelar Evento");
		button_4.setImmediate(false);
		button_4.setWidth("207px");
		button_4.setHeight("-1px");
		absoluteLayout_2.addComponent(button_4, "top:333.0px;left:180.0px;");
		
		return absoluteLayout_2;
	}

}
